#properties for the DEV environment

api:
  id: "000000"

application:
  name: "prod-helloworld-sys-app"


timeZone: "America/Los_Angeles"

#Common HTTP Listener Configuration Properties
http:
  protocol: "HTTP"
  host: "0.0.0.0"
  port: "8086"
  
exampleValue: "![xnwnNzyvOUI=]"      
appEnvironment: "prod"

scheduler:
  main:
    frequency: "0 0/1 * * * ?"
    maxconcurrency: "1"